import fs from 'node:fs';
fs.mkdirSync(new URL('../supabase/migrations/', import.meta.url), { recursive: true });
for (const [name, parts] of [
  ['supabase_schema.sql', ['base-schema.sql', 'production-compat.sql', 'security.sql', 'fresh-hooks.sql']],
  ['supabase/migrations/20260924_p1_security.sql', ['migration-guard.sql', 'production-compat.sql', 'security.sql']],
]) {
  const sql = '-- Generated by node scripts/build-schema.mjs. Edit supabase/*.sql sources.\nBEGIN;\n\n' +
    parts.map(part => `-- Source: supabase/${part}\n${fs.readFileSync(new URL('../supabase/' + part, import.meta.url), 'utf8')}`).join('\n\n') + '\nCOMMIT;\n';
  fs.writeFileSync(new URL('../' + name, import.meta.url), sql);
}
const verification = fs.readFileSync(new URL('../supabase/verification-body.sql',import.meta.url),'utf8');
const finish = "\nROLLBACK;\nSELECT 'PASS: test data rolled back; no test users or balances retained' AS result;\n";
fs.writeFileSync(new URL('../supabase/verify-p1.sql',import.meta.url),'BEGIN;\n'+verification+finish);
// Keep SQL that depends on newly-created objects inside EXECUTE so it is parsed
// when its stage runs, not before earlier stages have created those objects.
// On hosted PostgreSQL, retain the original error context (including DDL hooks).
function stage(name, sql) {
  if (sql.includes('$p1_sql$') || sql.includes('$p1_stage$')) throw new Error('Reserved SQL delimiter');
  return `\nDO $p1_stage$
DECLARE error_context TEXT; error_detail TEXT; error_hint TEXT;
BEGIN
  EXECUTE $p1_sql$${sql}$p1_sql$;
EXCEPTION WHEN OTHERS THEN
  GET STACKED DIAGNOSTICS error_context = PG_EXCEPTION_CONTEXT,
    error_detail = PG_EXCEPTION_DETAIL, error_hint = PG_EXCEPTION_HINT;
  RAISE EXCEPTION USING ERRCODE = SQLSTATE,
    MESSAGE = 'P1 dry-run stage: ${name} [' || SQLSTATE || '] ' || SQLERRM,
    DETAIL = coalesce(error_detail,'') || E'\\n' || coalesce(error_context,''),
    HINT = 'Copy this complete error (including DETAIL/CONTEXT). ' || coalesce(error_hint,'');
END $p1_stage$;\n`;
}
const dryRun = [
  ['01 schema check', fs.readFileSync(new URL('../supabase/migration-guard.sql',import.meta.url),'utf8')],
  ['02 private schema', 'CREATE SCHEMA IF NOT EXISTS private; REVOKE ALL ON SCHEMA private FROM PUBLIC;'],
  ['03 compatibility', fs.readFileSync(new URL('../supabase/production-compat.sql',import.meta.url),'utf8')],
  ['04 permissions and RPCs', fs.readFileSync(new URL('../supabase/security.sql',import.meta.url),'utf8')],
  ['05 verification', verification],
].map(([name,sql]) => stage(name,sql)).join('\n');
fs.writeFileSync(new URL('../supabase/dry-run-p1.sql',import.meta.url),
  '-- P1 DRY RUN v2: execute the WHOLE file, without selecting a fragment.\n' +
  '-- Migration and all synthetic test records are rolled back.\nBEGIN;\n' + dryRun + finish);
